# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: images.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cimages.proto\"\x14\n\x03img\x12\r\n\x05image\x18\x01 \x01(\t\"\x15\n\x06number\x12\x0b\n\x03num\x18\x01 \x01(\x05\x32)\n\x0bsend_images\x12\x1a\n\tsendImage\x12\x04.img\x1a\x07.numberb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'images_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMG._serialized_start=16
  _IMG._serialized_end=36
  _NUMBER._serialized_start=38
  _NUMBER._serialized_end=59
  _SEND_IMAGES._serialized_start=61
  _SEND_IMAGES._serialized_end=102
# @@protoc_insertion_point(module_scope)
