# Generated by Django 4.1.7 on 2023-03-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Forest_Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Image",
                    models.ImageField(
                        height_field=256, upload_to="Images", width_field=256
                    ),
                ),
            ],
        ),
    ]
