# Generated by Django 4.1.7 on 2023-03-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_SpaceImage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forest_images',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='forest_images',
            table='Forest_Images',
        ),
    ]
