# Generated by Django 4.1.7 on 2023-03-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_SpaceImage', '0002_alter_forest_images_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forest_images',
            name='Title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
