# Generated by Django 4.1.7 on 2023-03-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_SpaceImage', '0003_forest_images_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forest_images',
            name='Title',
        ),
    ]
