# Generated by Django 4.1.7 on 2023-03-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_SpaceImage', '0004_remove_forest_images_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forest_images',
            name='Image',
            field=models.ImageField(height_field=257, upload_to='Images', width_field=257),
        ),
    ]
