# Generated by Django 4.1.7 on 2023-03-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_SpaceImage', '0005_alter_forest_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forest_images',
            name='Image',
            field=models.ImageField(upload_to='Images'),
        ),
    ]
