# Generated by Django 4.1.7 on 2023-03-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_SpaceImage', '0013_saved_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALL_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Images')),
                ('Type', models.IntegerField(db_column='ID_Type')),
            ],
            options={
                'db_table': 'ALL_Images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Types_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(db_column='Type', max_length=20)),
            ],
            options={
                'db_table': 'Types_Images',
                'managed': True,
            },
        ),
    ]
