# Generated by Django 4.2 on 2023-05-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_SpaceImage', '0014_all_images_types_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_images',
            name='UsersID',
            field=models.IntegerField(db_column='ID_User', default=1),
            preserve_default=False,
        ),
    ]
